---
title: "Exercises Chapter 2"
author: "JC"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(baseballr)
```

3.1)

```{r}
percents <- c(.5,.6,.4,.3)
counts <- c(200,250,300,250)
total_count <- sum(counts)
percents;counts;total_count
```

```{r}
weights <- counts/total_count;
weights
```

```{r}
weighted_average <- sum(percents*counts/total_count)
weighted_average
```

3.2)

```{r}
new_weights <- c(.15,.15,.25,.45)
sum(new_weights*percents)
```

3.4)

```{r}

lambda <- 3.5

x <- 0:15
y <- dpois(x, lambda)

plot(x, y,
     type = "h",
     lwd = 2,
     xlab = "x",
     ylab = "P(X = x)",
     main = paste("Poisson Distribution (lambda =", lambda, ")"))
points(x, y, pch = 16)

```

```{r}
library(tidyverse)

lambda <- 4

df <- tibble(
  x = 0:15,
  prob = dpois(x, lambda)
)

ggplot(df, aes(x, prob)) +
  geom_col(fill = "steelblue") +
  labs(
    title = paste("Poisson Distribution (λ =", lambda, ")"),
    x = "Count",
    y = "Probability"
  ) +
  theme_minimal()
```

3.6)

a\)

```{r}
x = rnorm(2000,mean = 35, sd = 10)
y = 47.5 + 3/2*x
plot(x,y)
```

3.8)

```{r}
mu_male <- 69.1
sd_male <- 2.9

mu_female <- 63.7
sd_female <- 2.7

correlation <- .3

mu_avg <- (mu_male + mu_female)/2
sd_avg <- sqrt(.5^2*sd_male^2 + .5^2*sd_female^2 + .5^2*2*sd_male*sd_female*correlation)
mu_avg;sd_avg
```
